spring:
  cloud:
    config:
      server:
        git:
           uri: file:C:/Users/rafael.oliveira/Documents/Workspaces/WorkspaceMicroservices/spring-boot-microservices/sample-config
#          uri: https://github.com/anilallewar/sample-config
# While in development mode, you can configure the config server to pick up configuration files from
# the file system
          

# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8000          