spring:
  cloud:
    config:
      server:
        git:
           uri: file://Users/rafoli/Documents/Workspaces/Study/microus-samples-config
           #uri: https://github.com/rafoli/microus-samples-config

server:
  port: 8888        