spring:
  cloud:
    config:
      server:
        git:
           uri: file:/Users/rafoli/Documents/Workspaces/Study/microus-sample-config
           #uri: file:C:/Users/rafael.oliveira/Documents/Workspaces/WorkspaceMicroservices/microus/microus-configserver/src/main/resources/confs
server:
  port: 8888        